config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'trips#index'

  resources :trips do 
    resources :locations
  end 

  resources :locations do 
    resources :addresses
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :location
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :trip 
  has_one :address 
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user 
  has_many :locations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips 
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_location 
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  def index
    @addresses = @location.addresses
  end

  def show

  end


  def new
    @address = Address.new 
  end

  def create
    @address = Address.new(address_params)
    @location.address = @address 
      if @address.save 
        redirect_to trip_location_path(@location.trip_id, @location) 
      else 
        render :new
      end 
  end

  def edit
    @address = Address.find(params[:id])

  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to trip_location_path(@location.trip_id, @location) 
    else 
      render :edit
    end 
  end

  def destroy 
    @address.destroy 
    redirect_to trip_location_path(@location.trip_id, @location) 
  end

  private 

  def address_params
    params.require(:address).permit(:country, :state, :city, :street)
  end

  def set_location
    @location = Location.find(params[:location_id])
  end

  def set_address
    @address= Address.find(params[:id])
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!


end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_trip
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = @trip.locations
  end

  def show
  end

  def edit
    
  end

  def new
    @location = @trip.locations.new
    
  end

  def create
    @location = @trip.locations.new(location_params)

    if @location.save
      redirect_to [@trip, @location]
    else
      render :new
    end
  end

  def update
    if @location.update(location_params)
      redirect_to [@trip, @location]
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to trip_locations_path(@trip)
  end

  private

    def set_trip
      @trip = Trip.find(params[:trip_id])
    end

    def set_location
      @location= @trip.locations.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:name)
    end


end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = current_user.trips 
  end

  def show
    
  end

  def new
    @trip = Trip.new 
  end
  
  def create
    @trip = current_user.trips.new(trip_params)
      if @trip.save 
        redirect_to trips_path
      else 
        render :new 
      end
  end 

  def edit
    
  end

  def update
    if @trip.update(trip_params)
      redirect_to @trip 
    else 
      render :edit 
    end
  end


  def destroy 
    @trip.destroy 
      redirect_to trips_path 
  end

  private 

  def trip_params 
    params.require(:trip).permit(:name, :description)
  end

  def set_trip
    @trip = current_user.trips.find(params[:id]) 
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: [@location, @address], local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country, required: true, placeholder: "Country" %>
  </div>
  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state, required: true, placeholder: "State" %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city, required: true, placeholder: "City" %>
  </div>
  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street, required: true, placeholder: "Street" %>
  </div>
  <%= f.submit class: "ui green button" %>
  <% end %> 

app/views/addresses/edit.html.erb
<h1>Edit <%= @location.address.country %></h1>
<hr />
<%= render "form" %> 

app/views/addresses/index.html.erb
<h1>Addresses#index</h1>
<p>Find me in app/views/addresses/index.html.erb</p>

app/views/addresses/new.html.erb
<h1>New Addy</h1>
<hr />
<%= render "form" %> 

app/views/addresses/show.html.erb
<h1>Addresses#show</h1>
<p>Find me in app/views/addresses/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<div class="topnav">
  <%= link_to 'Trips', trips_path, class: "item" %>
  <a href="#about">About</a>
  <a href="#contact">Contact</a>
  
  <div class="right menu">
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "item" %>
  </div>
</div>  

<br/>
<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roadtrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: [@trip, @location], local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  
  <%= f.submit class: "ui green button" %>
  <% end %> 

app/views/locations/edit.html.erb
<h1> Edit <%= @trip.locations.name %> </h1>
<hr />

<%= render "form" %>

app/views/locations/index.html.erb
<h1> <%=@trip.locations.name%></h1>

<button class="ui green button">
<%= link_to 'Add New Location', new_trip_location_path(@trip) %>
</button >

<button class="ui button">
<%= link_to 'Back', trip_path(@trip) %>
</button>

<br />
<br />

<% @trip.locations.each do |t| %>
<li>
    <%= link_to t.name, trip_location_path(@trip, t) %>
</li>
<% end %> 

app/views/locations/new.html.erb
<h1> Add new location for <%=@trip.name%></h1>
<hr> 
<%= render "form" %> 

app/views/locations/show.html.erb
<h1> <%=@location.name%></h1>


<button class="ui button">
<%= link_to 'Delete', trip_location_path(@trip, @location), method: :delete %>
</button>
<% if @location.address %>
<button class="ui button">
<%= link_to "Edit", edit_trip_location_path(@trip, @location) %>
</button>
<% else %>
<button class="ui green button">
<%= link_to 'New Address', new_location_address_path(@location) %>
</button>
<% end %>
<button class="ui button">
<%= link_to 'Back',  trip_locations_path %>
</button>
<br />
<% if @location.address %>
<h4>Country: <%= @location.address.country %></h4>
<ul>
  <li>State: <%= @location.address.state %></li>
  <li>City: <%= @location.address.city %></li>
  <li>Street: <%= @location.address.street %></li>
</ul>
<% else %>
<%=  %> 
<% end %> 

app/views/trips/_form.html.erb
<%= form_with(model: @trip, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, required: true, placeholder: "Details about your trip..." %>
  </div>
  <%= f.submit class: "ui green button" %>
  <% end %> 

app/views/trips/edit.html.erb
<h1>Edit <%= @trip.name %></h1>
<hr />

<%= render "form" %>

app/views/trips/index.html.erb
<h1> Trips </h1>
<button class="ui green button">
<%= link_to 'Add New Trip', new_trip_path %>
</button>
<hr />
<body>
            <div class="ui cards">
            <% @trips.each do |t| %>
              <div class="card">
                <div class="content">
                  <div class="header"><%= link_to t.name , trip_path(t) %></div>
                  <div class="description">
                    <%= link_to t.description , trip_path(t) %>
                  </div>
                </div>
              </div>
              <% end %>
            </div>

app/views/trips/new.html.erb
<h1> New Trip </h1>
<hr />

<%= render "form" %>

app/views/trips/show.html.erb
<h3> <%= @trip.name %>
<hr />

<div>

  <button class="ui green button">
    <%=link_to "Add Location", new_trip_location_path(@trip)%>
  </button>

  <button class="ui button">
    <%=link_to "Delete", trip_path(@trip), method: :delete %> 
  </button>

  <button class="ui button">
    <%= link_to 'Edit', edit_trip_path(@trip) %>
  </button>

  <button class="ui button">
    <%= link_to 'Back', trips_path(@trip) %>
  </button>

    <input type="text" placeholder="Search..">

</div>

<br/>
<br/>

<div class="ui grid">
  <div class="four wide column">
    <div class="ui vertical fluid tabular menu">
      <a class="description-tab active item">
        Description
      </a>
      <a class="location-tab item">
        Locations
      </a>
      
    </div>
  </div>

  <div class="twelve wide stretched column">
    <div class="description-segment ui segment">
      <%= @trip.description %>
    </div>

    <div class="location-segment ui segment hidden">
      <% @trip.locations.each do |l| %>
        <li>
            <%= l.name  %> || <%= link_to "Address", trip_location_path(@trip, l) %>
        </li>
      <% end %>

    </div>
    </div>
  </div>
  
<br/>

 
  <!--The div element for the map -->
  <div mapContainer>
    <div id="map"></div>
  </div>




<!-- got my API key. -->
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCkUOdZ5y7hMm0yrcCQoCvLwzdM6M8s5qk&callback=initMap">
</script>

<!-- This is just a static map// could be modified for user functionality
Would like Pins to populate for Trips/Locations/Addresses
 -->
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBNCH17EUl7Az-gLaFBoOQChN5jF0dUIN0&callback=initMap">
</script>


<script>
// Initialize and add the map
function initMap() {
  // The location of Uluru--- cant seem to change it. SLC=] is at 40.7608° N, 111.8910° W
  var uluru = {lat: -25.344, lng: 131.036};
  // The map, centered at Uluru
  var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 4, center: uluru});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: uluru, map: map});
}
</script>





<script>

/*
  select the html elements you want
  then assign them to a descriptive variable
*/
var descriptionTab = document.querySelector('.description-tab');
var locationTab = document.querySelector('.location-tab');
var descriptionSegment = document.querySelector('.description-segment');
var locationSegment = document.querySelector('.location-segment');

/*
  function to remove classes from other tabs
  and add it to the one clickeds
*/
var setToActive = function(e) {
  var button = e.target;
  // remove the active class from all other tabs here


  locationTab.classList.remove('active');
  descriptionTab.classList.remove('active');
  descriptionSegment.classList.remove('hidden');
  locationSegment.classList.remove('hidden');
  // add the class to the one just clicked
  if(e.target.classList.contains('description-tab')){
    locationSegment.classList.add('hidden');
  } else if(e.target.classList.contains('location-tab')){
    descriptionSegment.classList.add('hidden');
  }
  button.classList.add('active')
}

/*
  listen to the tabs "click" events,
*/
descriptionTab.addEventListener('click', setToActive);
locationTab.addEventListener('click', setToActive);
</script>